# Generated by Django 4.1.1 on 2022-10-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenzen',
            name='excused',
            field=models.BooleanField(default=False),
        ),
    ]
