# Generated by Django 4.1.1 on 2022-10-29 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_schoolclass_person_klasse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'verbose_name': 'School Class'},
        ),
    ]
