# Generated by Django 4.1.1 on 2022-10-29 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_student_is_student_alter_student_is_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_teacher',
        ),
    ]
