# Generated by Django 4.1.1 on 2022-10-29 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_schoolclass_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'verbose_name': 'School Clas'},
        ),
    ]
