# Generated by Django 4.1.1 on 2022-10-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_alter_schoolclass_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'verbose_name': 'School Class', 'verbose_name_plural': ''},
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='name',
            field=models.CharField(default='', max_length=5),
        ),
    ]
