# Generated by Django 4.1.1 on 2022-10-29 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_alter_schoolclass_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'verbose_name': 'School Class', 'verbose_name_plural': 'School Classes'},
        ),
    ]
