# Generated by Django 4.1.1 on 2022-11-11 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_alter_schoolclass_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.schoolclass'),
        ),
    ]
