# Generated by Django 4.1.1 on 2022-11-12 09:38

from django.db import migrations, models
import django.db.models.deletion
import mainApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_thema_test_thema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='thema',
            field=models.ForeignKey(blank=True, limit_choices_to={'thema': 'Kek'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.thema'),
        ),
    ]
