# Generated by Django 4.1.1 on 2022-11-12 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_alter_test_thema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='thema',
            field=models.ForeignKey(blank=True, default=1, limit_choices_to={'subject': models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.subject')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.thema'),
        ),
    ]
