# Generated by Django 4.1.1 on 2022-11-12 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_alter_test_thema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thema',
            options={'verbose_name': 'Thema', 'verbose_name_plural': 'Themen'},
        ),
    ]
