# Generated by Django 4.1.1 on 2022-12-07 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0033_test_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='school_class',
        ),
    ]
