# Generated by Django 4.1.1 on 2022-12-07 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0035_test_school_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='weight',
            field=models.FloatField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
