# Generated by Django 4.1.4 on 2022-12-31 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0040_remove_test_subject_alter_subject_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='klasse',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.schoolclass'),
        ),
    ]
