# Generated by Django 4.1.1 on 2022-12-28 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0042_alter_person_klasse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='street_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
