# Generated by Django 4.1.1 on 2022-12-28 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0043_alter_person_street_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='thema',
            name='created_at',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
