# Generated by Django 4.1.1 on 2023-01-01 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0045_alter_thema_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thema',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 13, 8, 18, 831554)),
        ),
    ]
