# Generated by Django 4.1.1 on 2023-01-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0048_absenzen_image_absenzen_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenzen',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='absenzen/'),
        ),
    ]
